### ISSUE TITLE
Trivial UI Issue - Advisories page

### ISSUE THREAD

**Issue by mingsheng88** [nodesecurity/nodesecurity.io#52]
Pagination is erroneous. There should be 6 pages, not 5.
On drop page (https://nodesecurity.io/advisories), 1 - 10 are displayed.
On click "Next" (https://nodesecurity.io/advisories?page=1), 21-30 are displayed.
On click "Back" (https://nodesecurity.io/advisories?page=2), 11-20 are displayed.

**Comment by evilpacket** [comment]
Thanks for pointing this out. The pagination was a very quick throw together that I made so that when we did the transition it would have something there instead of a giant list, but as you point out it's certainly wrong. I have a patch that should take care of it, at least it makes it better and should be deployed tomorrow. We'll have a better site in the future, for now this will at least be functional.

**Comment by evilpacket** [comment]
I deployed a fix that's better than what was there. We'll be pushing out a new site in the future where we will address this a bit better then.
